const fs = require('fs');
const assert = require('assert');

function solve(data: string) {
	const world = data.trim().split('\n').map(l => l.trim().split(''));

	let splittersHit = 0
	let beams = world[0].map(c => +(c === 'S'))
	for (let r = 0; world[r + 1]; r++) {
		let nextBeams = world[0].map(() => 0)
		for (let c = 0; c < beams.length; c++) {
			const count = beams[c]
			if (!count) continue;

			const next = world[r + 1][c];

			if (next === '.') {
				nextBeams[c] += count;
				continue
			}

			splittersHit++
			nextBeams[c - 1] += count
			nextBeams[c + 1] += count
		}
		beams.splice(0, beams.length, ...nextBeams)
	}
	return { splittersHit, timelines: beams.reduce((a, b) => a + b) };
}

function solveOne(data: string) {
	return solve(data).splittersHit
}


(() => {
	const data = fs.readFileSync(__dirname + '/input.in').toString();
	assert.deepStrictEqual(solveOne(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`), 21);
	console.log(solveOne(data));
})();


function solveTwo(data: string) {
	return solve(data).timelines
}


(() => {
	const data = fs.readFileSync(__dirname + '/input.in').toString();
	assert.deepStrictEqual(solveTwo(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`), 40);
	console.log(solveTwo(data));
})();

export { };